<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>html</string>
	</array>
	<key>name</key>
	<string>Bridge Html</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>\/\/.*</string>
			<key>name</key>
			<string>comment</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?&lt;!\\)\$\w+</string>
			<key>name</key>
			<string>keyword.language.bridge_html</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(?&lt;!\\)(\$)({)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.language.bridge_html</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(})</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.dart</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\@)(extends|include|for|(?:else\s*)?if|block)\s*(\()</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.language.bridge_html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
			</dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.dart</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.language.bridge_html</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(\@)(else|end\s*(?:for|if|block))</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.language.bridge_html</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(&lt;\s*\/)\s*([\w-]+)\s*(&gt;)</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(&lt;)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(\&gt;)</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>&lt;|\&gt;|\/</string>
					<key>name</key>
					<string>punctuation.terminator.dart</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;=&lt;)\w+</string>
					<key>name</key>
					<string>keyword.language.bridge_html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(?&lt;!\\)\$\w+</string>
					<key>name</key>
					<string>keyword.language.bridge_html</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>(?&lt;!\\)(\$)({)</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>keyword.language.bridge_html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.dart</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(})</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.dart</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>include</key>
							<string>source.dart</string>
						</dict>
					</array>
				</dict>
				<dict>
					<key>begin</key>
					<string>(\w+)(=)(['"])</string>
					<key>beginCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.language.bridge_html</string>
						</dict>
						<key>2</key>
						<dict>
							<key>name</key>
							<string>punctuation.terminator.dart</string>
						</dict>
						<key>3</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>end</key>
					<string>(\3)</string>
					<key>endCaptures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>string</string>
						</dict>
					</dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>match</key>
							<string>(?&lt;!\\)\$\w+</string>
							<key>name</key>
							<string>keyword.language.bridge_html</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>(?&lt;!\\)(\$)({)</string>
							<key>beginCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>keyword.language.bridge_html</string>
								</dict>
								<key>2</key>
								<dict>
									<key>name</key>
									<string>punctuation.terminator.dart</string>
								</dict>
							</dict>
							<key>end</key>
							<string>(})</string>
							<key>endCaptures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>punctuation.terminator.dart</string>
								</dict>
							</dict>
							<key>patterns</key>
							<array>
								<dict>
									<key>include</key>
									<string>source.dart</string>
								</dict>
							</array>
						</dict>
						<dict>
							<key>match</key>
							<string>.</string>
							<key>name</key>
							<string>string</string>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.bridge_html</string>
	<key>uuid</key>
	<string>8f087cf1-a5f1-4af5-96bc-f4d0f86ecf26</string>
</dict>
</plist>
